# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\van\Desktop\map_path\dei.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_BaseVerticalLayout(object):
    def setupUi(self, BaseVerticalLayout):
        BaseVerticalLayout.setObjectName("BaseVerticalLayout")
        BaseVerticalLayout.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(BaseVerticalLayout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(BaseVerticalLayout)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(BaseVerticalLayout)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(BaseVerticalLayout)
        QtCore.QMetaObject.connectSlotsByName(BaseVerticalLayout)

    def retranslateUi(self, BaseVerticalLayout):
        _translate = QtCore.QCoreApplication.translate
        BaseVerticalLayout.setWindowTitle(_translate("BaseVerticalLayout", "Form"))
        self.label.setText(_translate("BaseVerticalLayout", "通过 右键 -> 布局 -> 垂直布局"))
        self.pushButton.setText(_translate("BaseVerticalLayout", "底部按钮"))
